/* Generated by tools/update-firefox-query-stripping.ts; do not edit by hand. */
/**
 * Pinning Mozilla's policy keeps the same input deterministic across releases, avoids a runtime
 * policy request, and makes any expansion of default Clean behavior visible in review.
 */
export const firefoxQueryStrippingSnapshot = Object.freeze({
  source: Object.freeze({
    url: "https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/query-stripping/records",
    records: Object.freeze([
      Object.freeze({ id: "a61d2791-d7e1-42e6-9824-0dbe69c33b97", lastModified: 1694689843914 }),
      Object.freeze({ id: "85078bad-f31e-4d93-bb8a-81088b25d6dd", lastModified: 1678736907773 }),
      Object.freeze({ id: "76495cfc-fac9-4079-9b5f-9ff0784484de", lastModified: 1649762862679 }),
    ])
  }),
  recordsLastModified: 1694689843914,
  stripParameters: Object.freeze([
    "gclid",
    "dclid",
    "msclkid",
    "_openstat",
    "yclid",
    "wickedid",
    "twclid",
    "_hsenc",
    "__hssc",
    "__hstc",
    "__hsfp",
    "hsctatracking",
    "wbraid",
    "gbraid",
    "ysclid",
    "mc_eid",
    "oly_anon_id",
    "oly_enc_id",
    "__s",
    "vero_id",
    "mkt_tok",
    "fbclid",
  ]),
  allowBaseDomains: Object.freeze([
    "googleadservices.com",
  ])
});
